### ISSUE TITLE
assertThat and matchers

### ISSUE THREAD

**Issue by sbley** [junit-team/junit-framework#147]
Is there any plan to support Hamcrest matchers? Or some fluent api style similar to AssertJ?

If not, would you consider adding an assertThat method which is semantically equal to assertTrue, for better readability?

**Comment by bechte** [comment]
Hi Stefan

you can use both, Hamcrest and AssertJ, in JUnit5. Both frameworks have a simple assertThat method, that you can import and use if wanted.

Currently, we do not plan to support these frameworks within our own Assertions to avoid the dependencies. Still, one can use them very well.

Cheers. Stefan.

**Comment by sbrannen** [comment]
Closing this issue since there are no plans to include direct dependencies on third-party assertion libraries within JUnit 5.
