### ISSUE TITLE
org.opentest4j.AssertionFailedError contains expected/actual fields but they are not set

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit-framework#182]
I could found the only usage org.junit.gen5.api.Assertions#fail(java.lang.String) where the message is already formatted and no expected/actual is present

**Comment by jlink** [comment]
I think it's a duplicate of #138

**Comment by marcphilipp** [comment]
Yes, I think so, too.

**Comment by akozlova** [comment]
Sorry, missed that.

**Comment by marcphilipp** [comment]
No problem at all. :-)
