### ISSUE TITLE
Introduct 'delta' support in Assertions for doubles and floats

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit-framework#269]
## Status Quo

Unlike JUnit 4, the `assertEquals()` variants in `org.junit.gen5.api.Assertions` that accept `double` and `float` arguments currently do not support a _delta_. This omission was simply an oversight on our part.
## Deliverables
- [x] Add a `delta` argument to each of the existing `assertEquals()` variants in `org.junit.gen5.api.Assertions` that accept `double` and `float` arguments.

**Comment by sbrannen** [comment]
This issue is currently slated for 5.0.0-M2; however, if it is completed in time it may be included in 5.0.0-M1.

**Comment by lutovich** [comment]
I can start working on this issue today.

**Comment by sbrannen** [comment]
Great! 👍

**Comment by sbrannen** [comment]
Closing this issue since #270 was merged into `master` in 4ce7a0fc1f588948abfc334598533add203f2830.
