### ISSUE TITLE
Assertions.assertEquals() should not check identity

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit-framework#318]
JUnit 4 executes the following `equals` method and therefore exits with an AssertionError (and not with `fail`):

``` java
  @Test
  public void probe4() {
    Object object = new Object() {
      public boolean equals(Object obj) {
        throw new AssertionError(); // end-of-test
      }
    };
    Assert.assertEquals(object, object);
    Assert.fail("should not happen");
  }
```

JUnit Jupiter does not execute the `equals` method and therefore exits with `fail("should not happen")`:

``` java
  @Test
  void probeJupiter() {
    Object object = new Object() {
      public boolean equals(Object obj) {
        throw new AssertionError();
      }
    };
    Assertions.assertEquals(object, object);
    Assertions.fail("should not happen"); // end-of-test
  }
```

The Jupiter implementation delegates to `java.util.Objects.equals(a, b)` which uses a short-cut if a and b point to the same object:

``` java
public static boolean equals(Object a, Object b) {
  return (a == b) || (a != null && a.equals(b));
}
```

Is the change of behavior intended?
## Deliverables
- [x] Do not perform identity check in `assertEquals()`
- [x] Do not perform identity check in `assertNotEquals()`

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Good catch!

No, the difference in behavior was not intentional. So thanks for pointing it out.

**Comment by nicolaiparlog** [comment]
But what would be "the right way" to do it? Identical objects are necessarily equal so I'd say that the current behavior (via `Objects::equals`) isn't necessarily wrong.

**Comment by sormuras** [comment]
It's not wrong from a logical point-of-view, but in this context, I expect a test framework to always execute `equals()` ... to test the implementation of that method. If I wanted to check for identity, I'd use `assertSame`.

**Comment by sbrannen** [comment]
I agree with both you:

1. The way it's implemented now in JUnit Jupiter seems logical, natural.
1. However, it's not how JUnit 4 or AssertJ do it. Presumably other assertion frameworks forego identity checks as well, but I didn't investigate further.
1. As @sormuras pointed out, one should invoke `assertSame` if one is interested in checking for identity.

So, in summary, we will revert the behavior in JUnit Jupiter to align with JUnit 4, AssertJ, etc.

**Comment by sbrannen** [comment]
Update: the same _bug_ is applicable to `assertNotEquals()` as well.
