### ISSUE TITLE
Idea: Make Assertions an interface

### ISSUE THREAD

**Issue by martin-g** [junit-team/junit-framework#414]
Is it a good idea to make https://github.com/junit-team/junit5/blob/master/junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java an **interface** with static methods ?
Same for Assumptions.

This way I could have test class like:

``` java
class MyTest implements Assertions, Assumptions {
  @Test
  void doIt() {
     assumingThat(...);
     ...
     assertEquals(...);
  }
}
```

The benefit is saving the static imports for each and every method. Especially when I add `implements Assertions, Assumptions` to my base test class.

**Comment by mmichaelis** [comment]
Doesn't sound that bad and is at least worth to spend some thoughts on that:

* I would suggest to make the methods default methods (see [Default Methods (The Java™ Tutorials > Learning the Java Language > Interfaces and Inheritance)](https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html)) instead. This way you could even override it in your test and add some additional behavior.
* Having this we could also extend e. g. Assertions in a custom framework to provide more sophisticated ones: `MyBetterAssertions`.

I like the idea. Any other comments?

**Comment by martin-g** [comment]
Thanks, @mmichaelis !
I suggested *static* instead of *default* methods because JUnit 4 users are used to `import static org.junit.Assert.xyz`. With default methods you have the extra flexibility but one will have to either `implements Assertions` (as I'd do!) or create an instance of Assertions and use it.
In ScalaTest all such classes are traits, i.e. something like Java 8's interface with default methods, and it works pretty well!

**Comment by marcphilipp** [comment]
Thanks for the proposal, @martin-g!

IMHO Java developers are used to static imports. Importing them shouldn't be an issue with a decent IDE. And a test class really doesn't _implement_ `Assertions`.

> I would suggest to make the methods default methods [...] instead. This way you could even override it in your test and add some additional behavior.

Overriding assertion methods might be confusing to readers of your test code who assume that e.g. `assertEquals` means what it usually does.

> Having this we could also extend e. g. Assertions in a custom framework to provide more sophisticated ones: MyBetterAssertions.

Extending assertions in a custom framework sounds nice enough at first sight. However, over time this might be unnecessary coupling that might lead to conflicts between the base class and the extending class.

---

@junit-team/junit-lambda What do you think about this proposal?

**Comment by martin-g** [comment]
Thanks for the feedback, Marc!

Just to repeat my initial idea:
An interface with *static* methods would preserve the "static imports"
usage and will allow the "implements" usage.

**Comment by sbrannen** [comment]
> @junit-team/junit-lambda What do you think about this proposal?

Our utility classes should remain utility classes. We should not convert them to interfaces.

So, unless another member of @junit-team/junit-lambda objects, we should decline this proposal.

**Comment by marcphilipp** [comment]
> Our utility classes should remain utility classes. We should not convert them to interfaces.

Agreed.

**Comment by klopfdreh** [comment]
@martin-g : good suggestion. Even if this issue has been rejected you got my 👍
