### ISSUE TITLE
Document interoperability with third-party assertion Matchers in User Guide

### ISSUE THREAD

**Issue by toniedzwiedz** [junit-team/junit-framework#428]
I've been reading about JUnit 5 for a while and there's one thing I'm wondering about.

The [`Assertions`](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html) class seems to be the JUnit 5 equivalent of the [JUnit 4 `Assert` class](http://junit.org/junit4/javadoc/latest/org/junit/Assert.html)

I noticed that it doesn't support any replacement of the `assertThat` method which accepts a custom matcher that one can use to make the assertion more simple and readable.

I like the power of expressions that matchers provide, I'm a fan of the `assertThat` syntax and it's something that I'd like to keep using.

I've had a look at the [User Guide](http://junit.org/junit5/docs/current/user-guide) as well as the list of packages in the [Javadoc](http://junit.org/junit5/docs/current/api/overview-summary.html) but I couldn't find a single mention of matchers.

What's the team's view on using matchers? Are they going to be supported or replaced in favour of a different mechanism? Or is it that they are not to be part of the JUnit standard and should be confined to external libraries such as Hamcrest  (Given how [`assertThat` in JUnit 4 `Assert`](http://junit.org/junit4/javadoc/latest/org/junit/Assert.html#assertThat%28java.lang.String, T, org.hamcrest.Matcher%29) class introduces a dependency on Hamcrest)

If anything, it would be nice to refer to the subject somewhere in the documentation.

**Comment by marcphilipp** [comment]
You're right: The current user guide does not mention how to use Hamcrest matchers with JUnit 5.

You can absolutely use Hamcrest with JUnit 5, in the same way you can use AssertJ or Truth. Instead of staticly importing `assertThat` from `org.junit.Assert` switch to [`org.hamcrest.MatcherAssert`](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/MatcherAssert.html). We will document that in the user guide.

**Comment by smoyer64** [comment]
I've been successfully using the AssertJ matchers in my JUnit 5 tests.  And I've written a couple AssertJ extensions that also work fine with JUnit 5.

**Comment by toniedzwiedz** [comment]
Thanks, just gave it a try in the example project and it works fine with Hamcrest.

Mind if I have a stab at adding this to the docs? (As a short addendum to [Section 3.4](http://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions))

**Comment by sbrannen** [comment]
> Mind if I have a stab at adding this to the docs? (As a short addendum to Section 3.4)

No, of course we don't mind.

BTW, that's what the green "up-for-grabs" label on the right-hand side of the browser is meant to imply. 😉 

Go for it!

**Comment by sbrannen** [comment]
This issue is now _unassigned_.
