### ISSUE TITLE
Enable to specify expected exception message reg exp

### ISSUE THREAD

**Issue by ondrejlerch** [junit-team/junit-framework#459]
What we use in TestNG but miss in JUnit is possibility to specify expected exception message reg exp.

In our project we use 1 exception but throw 100s of different error codes, e.g. PROCESS_NOT_FOUND(66803), etc.

In our case, it does not make sense to create specific exception class for each such error code.

In our tests with TestNG we use:
@Test(expectedExceptionsMessageRegExp = "._errorCode=66803._")
public void testProcessNotFound() {
}

We would find it helpful if similar functionality would be added to JUnit5.

**Comment by ttddyy** [comment]
How about AssertJ `assertThatThrownBy`?
http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#exception-assertion

```java
@Test
public void testException() {
   assertThatThrownBy(() -> { throw new Exception("boom!"); }).isInstanceOf(Exception.class)
                                                             .hasMessageContaining("boom");
}
```

**Comment by schauder** [comment]
You can do something very similar with expectThrows: 

http://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions

**Comment by ondrejlerch** [comment]
I agree that expectThrows is exactly what I was looking for.

To me it looks better than TestNG expectedExceptionsMessageRegExp since it is more flexible. E.g. currently with TestNG we have error codes in enum (PROCESS_NOT_FOUND(66803)) but due to annotation restrictions have to copy&paste magic numbers (expectedExceptionsMessageRegExp = ".errorCode=66803."). This would be nicely solved with Junit5 expectThrows.

Also I like that I don't have to use another dependency (AssertJ).

So I no longer suggest expectedExceptionsMessageRegExp to be added to Junit5.

Thanks Jens Schauder.
