### ISSUE TITLE
Introduce Assertions.assertAll(Stream<Executable>)

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit-framework#464]
Two new signatures for assertAll() would be useful:

```
public static void assertAll(Stream<Executable> executables) throws org.opentest4j.MultipleFailuresError;

public static void assertAll(java.lang.String heading, Stream<Executable> executables) throws org.opentest4j.MultipleFailuresError;
```

When the Executable(s) enclosed by assertAll() are generated via a Stream, it's necessary to collect the Executable(s) and convert them to an array.

**Comment by sbrannen** [comment]
This is something I've been meaning to do anyway. So thanks for raising the issue. 👍

**Comment by sbrannen** [comment]
_in progress_
