### ISSUE TITLE
Split Assertions and AssertionsTests

### ISSUE THREAD

**Issue by bechte** [junit-team/junit-framework#509]
# Status Quo

The classes `Assertions` and `AssertionsTest` have been growing larger since the time they were created. The files are getting too large to keep them easy to maintain.
# Proposals
- Split `AssertionsTest` class into logical units, e.g. `AssertionsEqualsTests`, etc.
- Move private and package-private helper methods from `Assertions` into a package-private `AssertionsUtil` class

**Comment by jbduncan** [comment]
This sounds like a good idea to me! I agree that they're getting too large - they're so much so that sometimes I get confused and I have to retrace my steps to find particular methods.

**Comment by sbrannen** [comment]
SGTM 👍

**Comment by signed** [comment]
I like the approach hamcrest is taking with there [CoreMatchers](https://github.com/hamcrest/JavaHamcrest/blob/master/hamcrest-core/src/main/java/org/hamcrest/CoreMatchers.java) and [Matchers](https://github.com/hamcrest/JavaHamcrest/blob/master/hamcrest-library/src/main/java/org/hamcrest/Matchers.java) classes. They are just a collection of method delegating to the classes actually implementing the logic.

For the Assertions class this would translate to classes like AssertEquals, AssertSame, AssertArrayEquals, ....
And Assertions than just delegating to this classes.

**Comment by marcphilipp** [comment]
I think that sounds like a good idea!

**Comment by sbrannen** [comment]
Resolved in #550 and #559.
