### ISSUE TITLE
Link to AssertionFailedError in the Javadoc

### ISSUE THREAD

**Issue by ogregoire** [junit-team/junit-framework#560]
In the [Javadoc for the `Assertions` class](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html), the following is mentioned:

> A *failed* assertion will always throw `AssertionFailedError` or a subclass thereof.

Junit doesn't declare that `AssertionFailedError` class, nor does the JDK (see [Junit's Javadoc](http://junit.org/junit5/docs/current/api/allclasses-frame.html) and [JDK's Javadoc](http://docs.oracle.com/javase/8/docs/api/allclasses-frame.html)).

So where is that class defined? Can you please add links in the Javadoc to the class you're actually referencing? I think that simply finding the missing link will be enough in the Javadoc build.

**Comment by smoyer64** [comment]
You can find that class here:

https://github.com/ota4j-team/opentest4j/blob/b6305430b88f3036c71fcf3a20522bfc9c7bd498/src/main/java/org/opentest4j/AssertionFailedError.java

This is one of the few dependencies allowed by the JUnit 5 team.

**Comment by ogregoire** [comment]
Thank you, I know that: I've done my research before asking. But this specific piece of information is missing from the documentation itself. My request is that the documentation provides a link to the documentation, or at the very least provide the full name of the class (rather than the simple name). I want to be able to identify the class from the Javadoc. It's currently not possible.

**Comment by smoyer64** [comment]
See PR #561 ... the "simple name" has been replaced by the FQCN for AssertionFailedError in the TOC javadoc.

**Comment by marcphilipp** [comment]
Good catch! I think we should publish the Javadocs for opentest4j separately and then configure the Gradle Javadoc task to generate links to it.

**Comment by sbrannen** [comment]
> I think we should publish the Javadocs for opentest4j separately and then configure the Gradle Javadoc task to generate links to it. 

I agree. 👍

**Comment by marcphilipp** [comment]
This issue is blocked by ota4j-team/opentest4j#28.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
The latest snapshot Javadocs now link to Javadoc of OpenTest4J as well as the JDK APIs: http://junit.org/junit5/docs/snapshot/api/.

**Comment by ogregoire** [comment]
Wow, that was fast! Thank you very much! :-)

**Comment by sbrannen** [comment]
👍
