### ISSUE TITLE
Feature:  Add fail methods that accept Throwable to Assertions

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit-framework#656]
## Overview

- (X) **Feature request.** See issue #655.  As discussed in issue #655, providing ```Assertions.fail()``` methods that accept parameters of type ```Throwable``` provides convenience for certain test patterns.

## Deliverables

Add the following methods to the ```Assertions``` class:

- [x]  ```Assertions.fail(String message, Throwable cause);```
- [x]  ```Assertions.fail(Throwable cause);```

**Comment by marcphilipp** [comment]
Thanks for opening the issue! I'm putting it _up-for-grabs_ for now. Do you want to give it a go?

**Comment by smoyer64** [comment]
Yes ... you can assign this one to me as I think it will help me complete #343.
