### ISSUE TITLE
Unit test and document Assertions

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit-framework#76]
## Deliverables
- [x] Unit test all assertion methods in `Assertions`.
- [x] Document `Assertions` and all public assertion methods.
  - [x] Document that `assertThrows` should be used instead of `expectThrows` when it is sufficient to check for the class of the exception expected to be thrown.

**Comment by marcphilipp** [comment]
We should also document that

- [ ] `assertThrows` should be used instead of `expectThrows` when it is sufficient to check for the class of the exception expected to be thrown.

**Comment by sbrannen** [comment]
True. Thanks for documenting that need. And... I see you've been reading my comments elsewhere. ;)

**Comment by jlink** [comment]
Done

**Comment by marcphilipp** [comment]
Are there unit tests for all assertion methods now?

**Comment by jlink** [comment]
Missing Tests for:
- [ ] fail(Supplier<String> messageSupplier)
- [ ] assertTrue(BooleanSupplier booleanSupplier, String message)
- [ ] assertFalse() in all variants
- [ ] assertNull(Object actual, String message)
- [ ] assertEquals(Object expected, Object actual, Supplier<String> messageSupplier) failing
- [ ] assertNotEquals(Object unexpected, Object actual, String message)
- [ ] assertSame(Object expected, Object actual, Supplier<String> messageSupplier) failing
- [ ] assertNotSame(Object unexpected, Object actual, String message)

**Comment by jlink** [comment]
Checking the `AssertionsTests` itself, most (if not all) of the list has already been covered a while ago.
What do I miss?

**Comment by marcphilipp** [comment]
I've verified that `fail(Supplier)` (for instance) is actually called and opened an issue with JaCoCo at jacoco/jacoco#370.

**Comment by sbrannen** [comment]
Thanks for raising the issue with the JaCoCo team!

**Comment by jlink** [comment]
Looking at the tests we can probably close this issue.

**Comment by sbrannen** [comment]
For a minute there... you guys had me worried that I didn't know how to write unit tests. So I'm relieved to know it's just an issue with JaCoCo. :wink: 

I concur: we can close this issue. So I'm doing that now.

**Comment by sbrannen** [comment]
@jlink, thanks for adding all of the Javadoc!
